### ISSUE TITLE
Suggestion for a possible improvement of the model

### ISSUE THREAD

**Issue by AndreaCovelli** [timonent/F1-bayesian-analysis#1]
The model is really interesting, such a great work considering that other mathematicians, such as Phillips (2014), haven't updated their models in the last years. 
As possible improvements to the model I would suggest taking into account these two variables:

1.  driver's car in each f1 season
2. the competitiveness of the grid in each year which according to studies by A.J.K. Phillips (2014) has increased over time since 1950 to the current times

Anyway, it's really a nice work, keep it up!

**Comment by tatutimonen** [comment]
Thanks for reaching out and for the kind words @AndJ23. I should note this research was performed as a graduate-level course work and is unlikely to receive further contributions from our side. However, the points you raise could indeed be interesting avenues to explore.
